import '@/styles/globals.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
import { Toaster } from 'react-hot-toast';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
