import { Metadata } from 'next';
import * as React from 'react';
import { Toaster } from 'react-hot-toast';

import '@/styles/globals.css';

import AdminNav from '@/components/admin/AdminNav';
import AdminSidebar from '@/components/admin/AdminSidebar';

import { montserrat } from '@/fonts/fonts';
import { getCurrentUser } from '@/utils/getCurrentUser';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html className={montserrat.variable}>
      <body>
        <Toaster
          toastOptions={{
            style: {
              background: 'rgb(51, 65, 85) ',
              color: '#fff',
            },
          }}
        />
        <AdminNav email={user?.email} />
        <div className='flex flex-row justify-start '>
          <AdminSidebar />
          <div className='flex-1 p-4'>{children}</div>
        </div>
      </body>
    </html>
  );
}
